#!/usr/bin/env node
'use strict'

const fs = require('fs')
const path = require('path')
const mkdirp = require('mkdirp')
const babel = require('babel-core')

const data = fs.readFileSync('README.md', 'utf8')

data.replace(/`[`]`js\s+\/\/\s*(\S+).*\n([\s\S]+?)`[`]`/g, (all, filename, contents) => {
  const targetFile = path.join('lib', filename)
  mkdirp.sync(path.dirname(targetFile))
  console.log('Writing %s', targetFile)
  const result = babel.transform(contents, {
    filename: targetFile,
    presets: [
      require('babel-preset-es2015'),
      require('babel-preset-stage-2')
    ]
  })
  fs.writeFileSync(targetFile, result.code)
})
